import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F9FAFB',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 16,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 2,
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1F2937',
    },
    headerActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    filterButton: {
        padding: 8,
        borderRadius: 8,
        backgroundColor: '#F3F4F6',
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    content: {
        flex: 1,
        paddingHorizontal: 16,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 40,
    },
    loadingText: {
        marginTop: 12,
        fontSize: 16,
        color: '#6B7280',
    },
    
    // Search and Filter Styles
    searchContainer: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    searchInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F9FAFB',
        borderRadius: 8,
        paddingHorizontal: 12,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    searchIcon: {
        marginRight: 8,
    },
    searchInput: {
        flex: 1,
        paddingVertical: 12,
        fontSize: 16,
        color: '#111827',
    },
    filtersContainer: {
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    filterRow: {
        marginBottom: 12,
    },
    filterGroup: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 12,
    },
    filterLabel: {
        fontSize: 15,
        fontWeight: '600',
        color: '#1F2937',
        marginRight: 12,
        minWidth: 60,
    },
    sortButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 18,
        paddingVertical: 12,
        borderRadius: 25,
        backgroundColor: '#F8FAFC',
        borderWidth: 2,
        borderColor: '#E2E8F0',
        gap: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 3,
        elevation: 2,
        minWidth: 80,
        justifyContent: 'center',
    },
    sortButtonActive: {
        backgroundColor: '#8B5CF6',
        borderColor: '#7C3AED',
        shadowColor: '#8B5CF6',
        shadowOpacity: 0.25,
        shadowRadius: 6,
        elevation: 4,
        transform: [{ scale: 1.02 }],
    },
    sortButtonText: {
        fontSize: 14,
        color: '#64748B',
        fontWeight: '600',
        textAlign: 'center',
    },
    sortButtonTextActive: {
        color: '#FFFFFF',
        fontWeight: '700',
    },
    statusFilterButton: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        backgroundColor: '#F3F4F6',
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    statusFilterActive: {
        backgroundColor: '#8B5CF6',
        borderColor: '#8B5CF6',
    },
    statusFilterText: {
        fontSize: 14,
        color: '#6B7280',
        fontWeight: '500',
    },
    statusFilterActiveText: {
        color: '#FFFFFF',
    },
    exportGroup: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 8,
    },
    exportActionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
        backgroundColor: '#F3F4F6',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        gap: 4,
    },
    exportActionText: {
        fontSize: 14,
        color: '#8B5CF6',
        fontWeight: '500',
    },
    summaryContainer: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        backgroundColor: '#F9FAFB',
    },
    summaryText: {
        fontSize: 14,
        color: '#6B7280',
        fontStyle: 'italic',
    },

    // Photo Grid Styles
    photoGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        paddingVertical: 16,
        gap: 12,
    },
    photoCard: {
        width: (width - 48) / 2, // 2 columns with padding
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        marginBottom: 16,
    },
    photoImageContainer: {
        position: 'relative',
        borderRadius: 8,
        overflow: 'hidden',
        marginBottom: 8,
    },
    photoImage: {
        width: '100%',
        height: 150,
        borderRadius: 8,
    },
    primaryBadge: {
        position: 'absolute',
        top: 8,
        left: 8,
        backgroundColor: '#F59E0B',
        borderRadius: 12,
        paddingHorizontal: 6,
        paddingVertical: 2,
        flexDirection: 'row',
        alignItems: 'center',
    },
    statusBadge: {
        position: 'absolute',
        bottom: 8,
        right: 8,
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 8,
    },
    statusActive: {
        backgroundColor: '#10B981',
    },
    statusReported: {
        backgroundColor: '#F59E0B',
    },
    statusRemoved: {
        backgroundColor: '#EF4444',
    },
    statusText: {
        fontSize: 10,
        color: '#FFFFFF',
        fontWeight: '600',
    },
    photoInfo: {
        marginBottom: 8,
    },
    photoUser: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 2,
    },
    photoEmail: {
        fontSize: 12,
        color: '#6B7280',
        marginBottom: 2,
    },
    reportCount: {
        fontSize: 12,
        color: '#EF4444',
        fontWeight: '500',
    },
    photoActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    actionButton: {
        padding: 8,
        borderRadius: 6,
        backgroundColor: '#F3F4F6',
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    deleteButton: {
        backgroundColor: '#FEF2F2',
        borderColor: '#FECACA',
    },

    // Pagination Styles
    paginationContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 16,
        backgroundColor: '#FFFFFF',
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
    },
    paginationButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 8,
        backgroundColor: '#F3F4F6',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        gap: 4,
    },
    paginationButtonDisabled: {
        backgroundColor: '#F9FAFB',
        borderColor: '#F3F4F6',
    },
    paginationButtonText: {
        fontSize: 14,
        color: '#8B5CF6',
        fontWeight: '500',
    },
    paginationButtonTextDisabled: {
        color: '#9CA3AF',
    },
    paginationInfo: {
        alignItems: 'center',
    },
    paginationText: {
        fontSize: 14,
        color: '#6B7280',
        fontWeight: '500',
    },

    // Modal Styles
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    photoModal: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        maxWidth: width - 40,
        maxHeight: '80%',
        overflow: 'hidden',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 8,
    },
    photoModalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
    },
    photoModalTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1F2937',
    },
    modalPhotoImage: {
        width: '100%',
        height: 250,
        borderRadius: 8,
        marginBottom: 16,
        resizeMode: 'contain',
    },
    photoModalContent: {
        padding: 20,
        flex: 1,
    },
    photoModalScrollView: {
        flex: 1,
    },
    photoDetails: {
        gap: 8,
        paddingBottom: 20,
    },
    detailLabel: {
        fontSize: 14,
        color: '#6B7280',
        fontWeight: '500',
    },
    detailValue: {
        color: '#1F2937',
        fontWeight: '600',
    },

    // Confirmation Modal Styles
    confirmOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    confirmModal: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 24,
        alignItems: 'center',
        maxWidth: 320,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 8,
    },
    confirmTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1F2937',
        marginTop: 16,
        marginBottom: 8,
    },
    confirmMessage: {
        fontSize: 14,
        color: '#6B7280',
        textAlign: 'center',
        marginBottom: 24,
        lineHeight: 20,
    },
    confirmButtons: {
        flexDirection: 'row',
        gap: 12,
    },
    confirmCancel: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 8,
        backgroundColor: '#F3F4F6',
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    confirmCancelText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#6B7280',
    },
    confirmDelete: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 8,
        backgroundColor: '#EF4444',
        alignItems: 'center',
    },
    confirmDeleteText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#FFFFFF',
    },

    // UX & Security Styles
    buttonDisabled: {
        backgroundColor: '#F9FAFB',
        borderColor: '#F3F4F6',
        opacity: 0.6,
    },
    buttonTextDisabled: {
        color: '#9CA3AF',
    },
    alertContainer: {
        position: 'absolute',
        top: 60,
        left: 16,
        right: 16,
        zIndex: 1000,
        borderRadius: 8,
        paddingHorizontal: 16,
        paddingVertical: 12,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    successAlert: {
        backgroundColor: '#10B981',
    },
    errorAlert: {
        backgroundColor: '#EF4444',
    },
    alertText: {
        flex: 1,
        fontSize: 14,
        color: '#FFFFFF',
        fontWeight: '500',
    },
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 2000,
    },
    loadingContent: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        paddingHorizontal: 24,
        paddingVertical: 20,
        alignItems: 'center',
        gap: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 8,
    },
    loadingOverlayText: {
        fontSize: 16,
        color: '#374151',
        fontWeight: '500',
    },
});
