import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F9FAFB',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 16,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 2,
    },
    headerTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#1F2937',
    },
    headerActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    filterButton: {
        padding: 8,
        borderRadius: 8,
        backgroundColor: '#F3F4F6',
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    content: {
        flex: 1,
        paddingHorizontal: 8,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 40,
    },
    loadingText: {
        marginTop: 12,
        fontSize: 16,
        color: '#6B7280',
    },
    
    // add style after
    usersContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 12,
        paddingHorizontal: 4,
    },
    userCard: {
        flex: 1,
        backgroundColor: '#F9FAFB',
        borderRadius: 8,
        padding: 12,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    userHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 8,
    },
    userAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#8B5CF6',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    userAvatarText: {
        color: '#FFFFFF',
        fontSize: 16,
        fontWeight: 'bold',
    },
    userDetails: {
        gap: 4,
    },
    userDetailItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    userDetailText: {
        fontSize: 12,
        color: '#6B7280',
    },
    matchConnector: {
        marginHorizontal: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    matchStats: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 16,
        marginTop: 12,
        paddingTop: 12,
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
    },
    statItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    statText: {
        fontSize: 12,
        color: '#6B7280',
    },
    
    // View Modal Styles
    viewModalContainer: {
        padding: 16,
    },
    viewSection: {
        marginBottom: 24,
    },
    viewSectionTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1F2937',
        marginBottom: 16,
    },
    viewInfoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    viewLabel: {
        fontSize: 14,
        color: '#6B7280',
        fontWeight: '500',
    },
    viewValue: {
        fontSize: 14,
        color: '#1F2937',
        fontWeight: '600',
    },
    userDetailCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    userProfileHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 16,
    },
    userAvatarLarge: {
        width: 60,
        height: 60,
        borderRadius: 30,
        backgroundColor: '#8B5CF6',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 16,
    },
    userAvatarTextLarge: {
        color: '#FFFFFF',
        fontSize: 24,
        fontWeight: 'bold',
    },
    userProfileInfo: {
        flex: 1,
    },
    userProfileName: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#1F2937',
        marginBottom: 4,
    },
    userProfileEmail: {
        fontSize: 14,
        color: '#6B7280',
        marginBottom: 2,
    },
    userProfileDetail: {
        fontSize: 12,
        color: '#9CA3AF',
    },
    userProfileDetails: {
        gap: 8,
    },
    profileDetailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 6,
    },
    profileDetailLabel: {
        fontSize: 14,
        color: '#6B7280',
        fontWeight: '500',
        flex: 1,
    },
    profileDetailValue: {
        fontSize: 14,
        color: '#1F2937',
        fontWeight: '600',
        flex: 2,
        textAlign: 'right',
    },
    verificationStatus: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        flex: 2,
        justifyContent: 'flex-end',
    },
    matchIdContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    matchId: {
        fontSize: 16,
        fontWeight: 'bold',
        color: '#1F2937',
    },
    actionButtonText: {
        fontSize: 12,
        color: '#4B5563',
        fontWeight: '500',
        marginLeft: 4,
    },

    // Search and Filter Styles
    searchContainer: {
        paddingHorizontal: 16,
        paddingVertical: 12,
        backgroundColor: '#FFFFFF',
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    searchInputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#F9FAFB',
        borderRadius: 8,
        paddingHorizontal: 12,
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    searchIcon: {
        marginRight: 8,
    },
    searchInput: {
        flex: 1,
        paddingVertical: 12,
        fontSize: 16,
        color: '#111827',
    },
    filtersContainer: {
        backgroundColor: '#FFFFFF',
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    filterRow: {
        marginBottom: 12,
    },
    filterGroup: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 12,
    },
    filterLabel: {
        fontSize: 15,
        fontWeight: '600',
        color: '#1F2937',
        marginRight: 12,
        minWidth: 60,
    },
    sortButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 18,
        paddingVertical: 12,
        borderRadius: 25,
        backgroundColor: '#F8FAFC',
        borderWidth: 2,
        borderColor: '#E2E8F0',
        gap: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 3,
        elevation: 2,
        minWidth: 80,
        justifyContent: 'center',
    },
    sortButtonActive: {
        backgroundColor: '#8B5CF6',
        borderColor: '#7C3AED',
        shadowColor: '#8B5CF6',
        shadowOpacity: 0.25,
        shadowRadius: 6,
        elevation: 4,
        transform: [{ scale: 1.02 }],
    },
    sortButtonText: {
        fontSize: 14,
        color: '#64748B',
        fontWeight: '600',
        textAlign: 'center',
    },
    sortButtonTextActive: {
        color: '#FFFFFF',
        fontWeight: '700',
    },
    statusFilterButton: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        backgroundColor: '#F3F4F6',
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    statusFilterActive: {
        backgroundColor: '#8B5CF6',
        borderColor: '#8B5CF6',
    },
    statusFilterText: {
        fontSize: 14,
        color: '#6B7280',
        fontWeight: '500',
    },
    statusFilterActiveText: {
        color: '#FFFFFF',
    },
    exportGroup: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: 8,
    },
    exportActionButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 8,
        backgroundColor: '#F3F4F6',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        gap: 4,
    },
    exportActionText: {
        fontSize: 14,
        color: '#8B5CF6',
        fontWeight: '500',
    },
    summaryContainer: {
        paddingHorizontal: 16,
        paddingVertical: 8,
        backgroundColor: '#F9FAFB',
    },
    summaryText: {
        fontSize: 14,
        color: '#6B7280',
        fontStyle: 'italic',
    },

    // Match List Styles
    matchList: {
        paddingVertical: 16,
    },
    matchCard: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 16,
        marginBottom: 16,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
        borderWidth: 1,
        borderColor: '#F3F4F6',
    },
    matchHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 12,
    },
    matchUsers: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginRight: 12,
    },
    userInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        flex: 1,
    },
    // userAvatar: {
    //     width: 40,
    //     height: 40,
    //     borderRadius: 20,
    //     marginRight: 8,
    //     backgroundColor: '#F3F4F6',
    // },
    // userDetails: {
    //     flex: 1,
    // },
    userName: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 2,
        marginRight: 8,
    },
    userEmail: {
        fontSize: 12,
        color: '#6B7280',
    },
    // matchConnector: {
    //     paddingHorizontal: 8,
    //     alignItems: 'center',
    //     justifyContent: 'center',
    // },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
        gap: 4,
        minWidth: 80,
        justifyContent: 'center',
    },
    statusText: {
        fontSize: 10,
        color: '#FFFFFF',
        fontWeight: '600',
    },
    // matchStats: {
    //     flexDirection: 'row',
    //     alignItems: 'center',
    //     flexWrap: 'wrap',
    //     gap: 16,
    //     marginBottom: 12,
    //     paddingVertical: 8,
    //     borderTopWidth: 1,
    //     borderTopColor: '#F3F4F6',
    // },
    // statItem: {
    //     flexDirection: 'row',
    //     alignItems: 'center',
    //     gap: 4,
    // },
    // statText: {
    //     fontSize: 12,
    //     color: '#6B7280',
    //     fontWeight: '500',
    // },
    matchActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        alignItems: 'center',
        gap: 8,
        paddingTop: 8,
        borderTopWidth: 1,
        borderTopColor: '#F3F4F6',
    },
    actionButton: {
        padding: 8,
        borderRadius: 6,
        backgroundColor: '#F3F4F6',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        alignItems: 'center',
        justifyContent: 'center',
    },
    deleteButton: {
        backgroundColor: '#FEF2F2',
        borderColor: '#FECACA',
    },

    // Pagination Styles
    paginationContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 16,
        backgroundColor: '#FFFFFF',
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
    },
    paginationButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 8,
        borderRadius: 8,
        backgroundColor: '#F3F4F6',
        borderWidth: 1,
        borderColor: '#E5E7EB',
        gap: 4,
    },
    paginationButtonDisabled: {
        backgroundColor: '#F9FAFB',
        borderColor: '#F3F4F6',
    },
    paginationButtonText: {
        fontSize: 14,
        color: '#8B5CF6',
        fontWeight: '500',
    },
    paginationButtonTextDisabled: {
        color: '#9CA3AF',
    },
    paginationInfo: {
        alignItems: 'center',
    },
    paginationText: {
        fontSize: 14,
        color: '#6B7280',
        fontWeight: '500',
    },

    // Modal Styles
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    matchModal: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 20,
        maxWidth: width - 40,
        maxHeight: '80%',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 8,
        minWidth: 300,
    },
    matchModalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#E5E7EB',
    },
    matchModalTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1F2937',
    },
    matchDetails: {
        maxHeight: 400,
    },
    detailSection: {
        marginBottom: 16,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: '#F3F4F6',
    },
    // Form styles for CRUD operations
    formContainer: {
        flex: 1,
        padding: 16,
    },
    formGroup: {
        marginBottom: 16,
    },
    formLabel: {
        fontSize: 14,
        fontWeight: '500',
        color: '#4B5563',
        marginBottom: 8,
    },
    requiredLabel: {
        color: '#EF4444',
    },
    formInput: {
        backgroundColor: '#FFFFFF',
        borderWidth: 1,
        borderColor: '#D1D5DB',
        borderRadius: 8,
        padding: 12,
        fontSize: 14,
        color: '#1F2937',
    },
    formInputDisabled: {
        backgroundColor: '#F3F4F6',
        color: '#6B7280',
    },
    formButtonGroup: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        marginBottom: 8,
    },
    formButton: {
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 6,
        backgroundColor: '#F3F4F6',
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    formButtonActive: {
        backgroundColor: '#3B82F6',
        borderColor: '#2563EB',
    },
    formButtonText: {
        fontSize: 14,
        color: '#4B5563',
    },
    formButtonTextActive: {
        color: '#FFFFFF',
        fontWeight: '500',
    },
    // Modal action buttons
    modalActionContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 12,
        marginTop: 24,
        paddingTop: 16,
        borderTopWidth: 1,
        borderTopColor: '#E5E7EB',
    },
    modalCancelButton: {
        flex: 1,
        backgroundColor: '#F3F4F6',
        padding: 12,
        borderRadius: 8,
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    modalCancelButtonText: {
        color: '#4B5563',
        fontWeight: '500',
        fontSize: 14,
    },
    modalSubmitButton: {
        flex: 1,
        backgroundColor: '#3B82F6',
        padding: 12,
        borderRadius: 8,
        alignItems: 'center',
    },
    modalSubmitButtonDisabled: {
        opacity: 0.5,
    },
    modalSubmitButtonText: {
        color: '#FFFFFF',
        fontWeight: '500',
        fontSize: 14,
    },
    modalSubmitButtonTextDisabled: {
        color: '#9CA3AF',
    },
    // Delete modal specific styles
    deleteModalContainer: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        padding: 24,
        alignItems: 'center',
        marginBottom: 24,
    },
    deleteWarningIcon: {
        alignSelf: 'center',
        marginBottom: 16,
    },
    deleteModalTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1F2937',
        textAlign: 'center',
        marginBottom: 16,
    },
    deleteModalMessage: {
        fontSize: 16,
        color: '#4B5563',
        textAlign: 'center',
        marginBottom: 8,
        lineHeight: 24,
    },
    deleteModalDetails: {
        fontSize: 14,
        color: '#6B7280',
        textAlign: 'center',
        marginBottom: 8,
    },
    deleteModalWarning: {
        fontSize: 14,
        color: '#EF4444',
        textAlign: 'center',
        marginTop: 12,
        fontWeight: '500',
    },
    deleteConfirmButton: {
        flex: 1,
        backgroundColor: '#EF4444',
        padding: 12,
        borderRadius: 8,
        alignItems: 'center',
    },
    deleteConfirmButtonText: {
        color: '#FFFFFF',
        fontWeight: '500',
        fontSize: 14,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1F2937',
        marginBottom: 8,
    },
    detailLabel: {
        fontSize: 14,
        color: '#6B7280',
        fontWeight: '500',
        marginBottom: 4,
        lineHeight: 20,
    },
    detailValue: {
        color: '#1F2937',
        fontWeight: '600',
    },

    // Confirmation Modal Styles
    confirmOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    confirmModal: {
        backgroundColor: '#FFFFFF',
        borderRadius: 16,
        padding: 24,
        alignItems: 'center',
        maxWidth: 320,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 8,
    },
    confirmTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#1F2937',
        marginTop: 16,
        marginBottom: 8,
        textAlign: 'center',
    },
    confirmMessage: {
        fontSize: 14,
        color: '#6B7280',
        textAlign: 'center',
        marginBottom: 24,
        lineHeight: 20,
    },
    confirmButtons: {
        flexDirection: 'row',
        gap: 12,
    },
    confirmCancel: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 8,
        backgroundColor: '#F3F4F6',
        borderWidth: 1,
        borderColor: '#E5E7EB',
    },
    confirmCancelText: {
        fontSize: 14,
        fontWeight: '500',
        color: '#6B7280',
    },
    confirmDelete: {
        paddingHorizontal: 20,
        paddingVertical: 10,
        borderRadius: 8,
        backgroundColor: '#EF4444',
        alignItems: 'center',
    },
    confirmDeleteText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#FFFFFF',
    },

    // UX & Security Styles
    buttonDisabled: {
        backgroundColor: '#F9FAFB',
        borderColor: '#F3F4F6',
        opacity: 0.6,
    },
    buttonTextDisabled: {
        color: '#9CA3AF',
    },
    alertContainer: {
        position: 'absolute',
        top: 60,
        left: 16,
        right: 16,
        zIndex: 1000,
        borderRadius: 8,
        paddingHorizontal: 16,
        paddingVertical: 12,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    successAlert: {
        backgroundColor: '#10B981',
    },
    errorAlert: {
        backgroundColor: '#EF4444',
    },
    alertText: {
        flex: 1,
        fontSize: 14,
        color: '#FFFFFF',
        fontWeight: '500',
    },
    loadingOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 2000,
    },
    loadingContent: {
        backgroundColor: '#FFFFFF',
        borderRadius: 12,
        paddingHorizontal: 24,
        paddingVertical: 20,
        alignItems: 'center',
        gap: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 8,
        elevation: 8,
    },
    loadingOverlayText: {
        fontSize: 16,
        color: '#374151',
        fontWeight: '500',
    },
    
    // Additional styles for form validation
    formInputError: {
        borderColor: '#EF4444',
        backgroundColor: '#FEF2F2',
    },
    formErrorText: {
        fontSize: 12,
        color: '#EF4444',
        marginTop: 4,
    },
    
    // Additional styles for action buttons
    // actionButtonText: {
    //     fontSize: 12,
    //     color: '#4B5563',
    //     fontWeight: '500',
    // },
    viewButton: {
        backgroundColor: '#EBF8FF',
        borderColor: '#BEE3F8',
    },
    cancelButton: {
        backgroundColor: '#FEF2F2',
        borderColor: '#FECACA',
    },
    
    // Additional styles for empty state
    emptyState: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingVertical: 40,
    },
    emptyStateText: {
        fontSize: 16,
        color: '#6B7280',
        marginTop: 12,
    },
    
    // Additional styles for scroll content
    scrollContent: {
        paddingBottom: 20,
    },
});
